### ISSUE TITLE
Pie chart labels overlap

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#14]
1. Pie chart tags are overlapped and not visible. 
To fix it, add a legend with the WT causes below the chart (see the legend in the _Waiting time causes in activity transitions_ graph for reference). Note that in the labels for the waiting time causes (resource unavailability, resource contention), only the first word has a capitalization of the first letter. 
In the pie chart, leave the values of the WT causes.
Test on the _Device Repair.csv_ and the _production.csv_ logs to verify the fix works. If you have concerns, contact me with questions.

2. The pie chart must be centered. Make sure the text labels and values in the pie chart are visible in different event logs.

In the figure, the result for the Device Repair.csv
<img width="522" alt="Screenshot 2022-12-15 at 15 28 47" src="https://user-images.githubusercontent.com/83600435/207871098-20d03bfd-c59a-40d9-9233-3eb938bc0772.png">

**Comment by JonasBerx** [comment]
Resolved: New chart introduced
Result example in image
![image](https://user-images.githubusercontent.com/43341402/214253318-b5cf0f0a-e50a-4603-94fc-642b2139e8d9.png)

**Comment by katelashkevich** [comment]
Tested: success.
