### ISSUE TITLE
Pie chart percentages

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#15]
In the pie chart, along with the absolute values, the percentages for each wt cause should be displayed. 
For that, add the percentages to the graph on hover, e.g.:
<img width="275" alt="Screenshot 2022-12-15 at 15 37 08" src="https://user-images.githubusercontent.com/83600435/207872853-2d2332a3-151f-4326-a9a2-a37b02b2fea9.png">

**Comment by JonasBerx** [comment]
Resolved - Refer to #14 for result example

**Comment by katelashkevich** [comment]
Tested: success.
