### ISSUE TITLE
Waiting time causes in activity transitions graph

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#16]
The _Waiting time causes in activity transitions_ graph requires the following updates: 
1. Display 10 transitions (bars) on default with no opportunity to change (scroll cannot be resized by the user). 
2. Use a smaller font size for the labels of the activity transition names (Marlon suggested "the smallest reasonable", however, I do not have an exact size). Limit the amount of the displayed characters (approx. 20) and hide the rest of the characters under the dots (...). In addition, add hover. On hover, display the full names of the activity transitions. 

In the figure, the result for the Procure-to-Pay.csv.
<img width="950" alt="Screenshot 2022-12-15 at 16 17 16" src="https://user-images.githubusercontent.com/83600435/207883916-1e762de8-dc55-4171-a2c6-a2a72fb057ce.png">

3. If possible, use a vertical scroll instead of the horizontal one. If not possible, leave it horizontal.

**Comment by JonasBerx** [comment]
Resolved: new chart introduced.

1. a maximum of 9 bars will be shown at a time (most reasonable / visually appealing option)
2. 

Question for @katelashkevich : Do you want the bar labels enabled or disabled? See below pictures for reference
![image](https://user-images.githubusercontent.com/43341402/214255041-12ebc916-217c-4c62-b7f7-c6f4d2bede88.png)
![image](https://user-images.githubusercontent.com/43341402/214255443-22f5a98c-26d7-4961-9f02-312378ec5b64.png)

--

# Tooltip example:
![image](https://user-images.githubusercontent.com/43341402/214256932-10566887-9539-4b12-8253-8b3c7ba31674.png)

**Comment by katelashkevich** [comment]
The current implementation, according to the tooltip example, looks good. 
Tested: success.
