### ISSUE TITLE
Activity names in the Transitions table

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#17]
Sometimes, if the activity name is long, it is not fully visible in the table. 
If possible, display the full activity names on hover. 

In the picture, the result for the _Procure-to-Pay.csv_ log. 
<img width="1442" alt="Screenshot 2022-12-15 at 17 01 47" src="https://user-images.githubusercontent.com/83600435/207894288-50eb1b48-3c49-4f8d-b42e-97f3e3268a43.png">

**Comment by JonasBerx** [comment]
Cannot be resolved at this time.
React MUI (Library used for the entire project + Prosimos) has the resizing of table columns locked behind a commercial/paid version of the library.
I've resized the columns so the Activity names have the most space possible without reducing readability of the other columns.

-> Once we would get a commercial license for this library, resizing is just a parameter to add.

**Comment by katelashkevich** [comment]
Accepted.
