### ISSUE TITLE
Detailed info in the Transitions table

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#19]
In the Transitions table, a pop-up with detailed information about the selected transition requires the following changes: 
1. a subtitle update is required: Waiting times per resource pairs in the selected transition, 
2. align the column widths with the ones in the _Transitions_ table,
3. label "Cases" -> "Total frequency" (yes, changing it back based on the received feedback),
4. align the order of the columns with the one in the _Transitions_ table. More specifically, ... "batching," "prioritization," "resource contention,"...
5. align the wt cause labels with the ones in the _Transitions_ table, e.g., "R. Contention" instead of "Resource conte..."

In the figure, the results for the production.csv
<img width="953" alt="Screenshot 2022-12-15 at 17 19 34" src="https://user-images.githubusercontent.com/83600435/207898389-2f3d3a74-a786-4b56-899d-97aa89d1e6b0.png">

**Comment by JonasBerx** [comment]
1. Resolved
2. Resolved
3. Resolved
4. Resolved
5. Resolved

![image](https://user-images.githubusercontent.com/43341402/214258015-75829cdb-0f52-4ec9-a2e1-9fe80a4b1b4a.png)

**Comment by katelashkevich** [comment]
Tested: success.
