### ISSUE TITLE
Hovers in the CTE impact graph 

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#20]
Texts on hover are not always fully visible. 
Reduce the font size and increase the width of the graph.

In the figure, the results for the Manual_log_5.csv
<img width="565" alt="Screenshot 2022-12-15 at 17 24 25" src="https://user-images.githubusercontent.com/83600435/207899547-61a78c36-0d1e-414f-9838-6924521e36ff.png">

**Comment by JonasBerx** [comment]
Resolved: New graph introduced + tooltip updated
![image](https://user-images.githubusercontent.com/43341402/214261841-4528b391-61b0-4a47-a680-646f020971b6.png)

**Comment by katelashkevich** [comment]
Tested: success.
