### ISSUE TITLE
CTE impact heatmap

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#23]
Currently, we have a heatmap in the table of the CTE impact per transition. Now we need to have a standalone graph (not inside the table in the pop-up but available on the page). 

The graph should display the top 10 transitions with the highest CTE improvement based on the total WT improvement. These data correspond to the top 10 rows of the CTE improvement table. 

If possible, update the heatmap design according to the prototype. If not, then see if smth similar can be done. The "Deterioration" option is not needed.

<img width="676" alt="Screenshot 2022-12-15 at 20 28 32" src="https://user-images.githubusercontent.com/83600435/207939210-0e70573f-c09e-431f-aa01-546f0f5e3f45.png">

**Comment by JonasBerx** [comment]
Resolved: New chart introduced with top 10 data.
![image](https://user-images.githubusercontent.com/43341402/214296257-f67153e3-5403-4f35-845f-4eed659199dd.png)

**Comment by katelashkevich** [comment]
Tested: success.
