### ISSUE TITLE
CTE improvement table 

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#24]
The CTE improvement table requires the following changes: 

1. Title: Potential CTE improvement per transition and waiting time cause
2. Remove the heatmap pop-up. 
3. Align the column widths with the ones in the _Transitions_ table. 
4. Align the column order and the column names with the ones in the _Transitions_ table (e.g., "Total Extrantious" -> "Extrantious") 
5. The format of the Case frequency should be the same as in the _Transitions_ table. Format: xx.xx% (two signs after the dot). 
6. Display 10 rows + pagination.

**Comment by JonasBerx** [comment]
1. Resolved (In subtable popup)
2. resolved
3. resolved
4. resolved
5. resolved
6. resolved

Main table
![image](https://user-images.githubusercontent.com/43341402/214264214-e7eb5879-c3e1-4b7f-9001-611b4b46be48.png)

subtable
![image](https://user-images.githubusercontent.com/43341402/214264709-a9470f6c-d3e1-4433-9503-397447854479.png)

**Comment by katelashkevich** [comment]
Tested: success.
