### ISSUE TITLE
Detailed info in the CTE impact table

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#25]
In the detailed information about the selected transition, 
1. update the subtitle: Potential CTE values per resource pairs if a particular waiting time is eliminated in the selected transition.
2. align the column widths, column names, and their order with the ones in the CTE impact table (from which the pop-up is called).
3. Total waiting time column is missing. By default, the table should be sorted by the Total waiting time in descending order. 

In the picture, the result for the Device.Repair.csv
<img width="1667" alt="Screenshot 2022-12-15 at 20 39 24" src="https://user-images.githubusercontent.com/83600435/207941131-d45250d3-c1a3-4b76-bc21-44fdecc8f836.png">

**Comment by JonasBerx** [comment]
Can you explain how Total Waiting time column should look?
Its a bit odd to put a column with absolute values in a table with only relative values.

**Comment by JonasBerx** [comment]
1. resolved
2. resolved
3. Is this what you are looking for then? Each column entry represents the WT produced between the two resources.
![image](https://user-images.githubusercontent.com/43341402/214267992-b4c9a654-c347-43cf-88f3-629b69c9ee68.png)

**Comment by katelashkevich** [comment]
As for the total waiting time. Here, it should also be in %. Similarly to other WT columns in this table, total WT should show the potential CTE of the process when the total WT in the selected transition performed by these resources is eliminated. I believe that Ihar should send this value. If it is not there, please ask him directly.

**Comment by JonasBerx** [comment]
Shouldnt this column then be called "potential CTE" instead of "Total WT?"

**Comment by JonasBerx** [comment]
This is how i interpret whats wished.
The value is calculated like this: Total PT / (Total Global WT - Total WT created by resource pair)
![image](https://user-images.githubusercontent.com/43341402/214583396-28d1a6e3-f4f8-49f8-b805-b4a5b0ffd99a.png)

**Comment by katelashkevich** [comment]
Total PT / (**Total PT** + Total Global WT - Total WT created by resource pair)

**Comment by JonasBerx** [comment]
Resolved

**Comment by katelashkevich** [comment]
Tested: success.
