### ISSUE TITLE
Minor style and text corrections

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#26]
1. Unify the text style in the entire tool, including: 
- font, 
- padding,
- size. 

Check the style of cards, tables and subtables, and graphs. 

2. Unify the capitalization of the words so that we have it everywhere the same way. Let us capitalize the first word only. Thus, unify to the following: 
- Resource contention and R. contention (in table headings)
- Resource unavailability and R. unavailability (in table headings)
- Prioritization (not Resource prioritization in the pie chart) 
- Source activity, Target activity, Source resource, Target resource 
- Case frequency, Total frequency, Total waiting time 
- CTE, Cycle time efficiency 

Check the capitalization in cards, tables and subtables, and graphs. 

3. Update text for the subheadings: 
- Transitions -> Table -> Subtable. Change subheading to:
   Waiting times per resource pair in the selected transition _(not pairs)_
- CTE impact -> Table "Potential CTE improvement per transition and waiting time cause" -> Subtable. Change subheading to:
   Potential CTE if waiting times of a particular cause are eliminated per resource pair in the selected transition
- CTE impact -> Graph "Potential CTE improvement per waiting time cause". Change subheading to:
   Potential CTE if waiting times of a particular cause are eliminated 

4. Update the title of the table "CTE per case" to "Top 50 cases with the lowest CTE". 

5. In the potential CTE graph, remove "% improvement". If cannot be removed, change to "CTE".
<img width="696" alt="Screenshot 2023-01-26 at 16 59 29" src="https://user-images.githubusercontent.com/83600435/214869429-145a7f92-2f01-4cc5-a614-2ab9c55f7dea.png">

**Comment by JonasBerx** [comment]
resolved

**Comment by katelashkevich** [comment]
Tested. 

1. Resource prioritization -> Prioritization (in the pie chart).
<img width="428" alt="Screenshot 2023-02-02 at 12 49 12" src="https://user-images.githubusercontent.com/83600435/216304713-854270c8-4e75-4adb-b375-ad6a8e28a14a.png">

2. Capitalizing. Should be Source activity, Case frequency (in the Transitions table). 
<img width="610" alt="Screenshot 2023-02-02 at 12 48 26" src="https://user-images.githubusercontent.com/83600435/216304558-8503e2f4-7e8d-44f0-8ff8-98810c3787b4.png">

3. Capitalizing. Only the first word should be capitalized (in the CTE impact table)
<img width="1440" alt="Screenshot 2023-02-02 at 12 51 44" src="https://user-images.githubusercontent.com/83600435/216305277-f0b01e97-1559-4ce0-a21c-020d048e6ca8.png">

... and in its subtable: -> Source resource, Target resource. 
<img width="611" alt="Screenshot 2023-02-02 at 12 53 17" src="https://user-images.githubusercontent.com/83600435/216305581-a21a51f2-f65e-44e5-9e8f-1422245a6270.png">

**Comment by JonasBerx** [comment]
fixed the ones i overlooked
