### ISSUE TITLE
No value for the current cte

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-frontend#30]
In the graph "potential cte improvement per waiting time cause", on hover over the bar "current cte" no value is displayed. On hover, the value should be displayed along with the bar's title. On hover over all other bars, no issues.

Current CTE (no value) 
<img width="655" alt="Screenshot 2023-03-02 at 14 10 24" src="https://user-images.githubusercontent.com/83600435/222425014-cb4ee4db-4bb0-46b8-976d-31ff2a840231.png">

Batching (ok)
<img width="608" alt="Screenshot 2023-03-02 at 14 12 03" src="https://user-images.githubusercontent.com/83600435/222425402-b74a9c26-adb8-48d0-9884-21f68194b6e7.png">

Tested on manual log 3. 
[manual_log_3.csv](https://github.com/AutomatedProcessImprovement/waiting-time-frontend/files/10871159/manual_log_3.csv)

**Comment by JonasBerx** [comment]
yep, did not add that properly, is fixed
